"""
printify_agent — uploads designs to Printify, creates products, and publishes
them to the connected Etsy store.

Blueprint reference (common):
  5   → Gildan 64000 Softstyle T-shirt
  282 → Matte Vertical Posters

Print provider reference (common):
  29  → Monster Digital   (t-shirts, US-based)
  99  → District Photo    (posters, US-based)
  36  → The Dream Junction (budget fallback)
"""

import base64
import os
import time
from pathlib import Path

import httpx

from utils.db import is_duplicate, track_listing
from utils.helpers import log_action

PRINTIFY_BASE = "https://api.printify.com/v1"

# Blueprint IDs — verified against live Printify catalog
BLUEPRINTS: dict[str, int] = {
    "t-shirt": 5,
    "poster":  282,   # Matte Vertical Posters (provider 99)
}

# Provider priority per product type (providers are blueprint-specific)
PROVIDER_PRIORITY: dict[str, list[int]] = {
    "t-shirt": [29, 36, 99],   # Monster Digital preferred for shirts
    "poster":  [99, 2],        # District Photo preferred for posters
}

_HEADERS: dict | None = None


def _headers() -> dict:
    global _HEADERS
    if _HEADERS is None:
        key = os.getenv("PRINTIFY_API_KEY", "")
        if not key:
            raise EnvironmentError("PRINTIFY_API_KEY is not set.")
        _HEADERS = {
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
            "User-Agent": "EtsyAgentLoop/1.0",
        }
    return _HEADERS


def _shop_id() -> str:
    sid = os.getenv("PRINTIFY_SHOP_ID", "")
    if not sid:
        raise EnvironmentError("PRINTIFY_SHOP_ID is not set.")
    return sid


# ── image upload ──────────────────────────────────────────────────────────────

def upload_image(image_path: str) -> str:
    """Upload a local PNG to Printify and return the image ID."""
    path = Path(image_path)
    with path.open("rb") as fh:
        contents = base64.b64encode(fh.read()).decode()

    r = httpx.post(
        f"{PRINTIFY_BASE}/uploads/images.json",
        headers=_headers(),
        json={"file_name": path.name, "contents": contents},
        timeout=120,
    )
    r.raise_for_status()
    image_id = r.json()["id"]
    log_action("printify_agent", f"Image uploaded → id={image_id}")
    return image_id


# ── blueprint helpers ─────────────────────────────────────────────────────────

def _get_variants(blueprint_id: int, provider_id: int) -> list[int]:
    """Return a list of variant IDs for the given blueprint + provider."""
    r = httpx.get(
        f"{PRINTIFY_BASE}/catalog/blueprints/{blueprint_id}"
        f"/print_providers/{provider_id}/variants.json",
        headers=_headers(),
        timeout=30,
    )
    r.raise_for_status()
    variants = r.json().get("variants", [])
    # For t-shirts: return S/M/L/XL/2XL — first 5 enabled variants
    return [v["id"] for v in variants if v.get("is_available", True)][:5]


def _find_working_provider(blueprint_id: int, product_type: str = "t-shirt") -> tuple[int, list[int]]:
    """Try providers in priority order for the given product type."""
    priority = PROVIDER_PRIORITY.get(product_type, PROVIDER_PRIORITY["t-shirt"])
    for pid in priority:
        try:
            variants = _get_variants(blueprint_id, pid)
            if variants:
                return pid, variants
        except Exception:
            continue
    raise RuntimeError(
        f"No working print provider found for blueprint {blueprint_id} ({product_type})"
    )


# ── product creation ──────────────────────────────────────────────────────────

def create_product(image_id: str, brief: dict, provider_id: int, variants: list[int]) -> dict:
    blueprint_id = BLUEPRINTS.get(brief.get("product_type", "t-shirt"), 5)
    price_cents  = int(float(brief.get("price_point", 24.99)) * 100)

    # Use SEO-optimised content generated by analyst; fall back gracefully
    title = (
        brief.get("seo_title")
        or brief.get("suggested_text")
        or brief.get("niche", "Custom Design")
    )[:140]

    description = (
        brief.get("seo_description")
        or f"A {brief.get('style', 'modern')} {brief.get('niche', 'design')} "
           f"printed on premium quality {brief.get('product_type', 'garment')}."
    )

    tags = [t[:20] for t in brief.get("seo_tags", [])[:13]]

    payload = {
        "title":             title,
        "description":       description,
        "tags":              tags,
        "blueprint_id":      blueprint_id,
        "print_provider_id": provider_id,
        "variants": [
            {"id": v, "price": price_cents, "is_enabled": True}
            for v in variants
        ],
        "print_areas": [
            {
                "variant_ids": variants,
                "placeholders": [
                    {
                        "position": "front",
                        "images": [
                            {
                                "id":    image_id,
                                "x":     0.5,
                                "y":     0.5,
                                "scale": 1.0,
                                "angle": 0,
                            }
                        ],
                    }
                ],
            }
        ],
    }

    r = httpx.post(
        f"{PRINTIFY_BASE}/shops/{_shop_id()}/products.json",
        headers=_headers(),
        json=payload,
        timeout=60,
    )
    r.raise_for_status()
    product = r.json()
    log_action("printify_agent", f"Product created → id={product['id']}")
    return product


# ── publish ───────────────────────────────────────────────────────────────────

def publish_product(product_id: str) -> dict:
    """Publish a Printify product to the connected Etsy store."""
    r = httpx.post(
        f"{PRINTIFY_BASE}/shops/{_shop_id()}/products/{product_id}/publish.json",
        headers=_headers(),
        json={
            "title":             True,
            "description":       True,
            "images":            True,
            "variants":          True,
            "tags":              True,
            "keyFeatures":       True,
            "shipping_template": True,
        },
        timeout=60,
    )
    r.raise_for_status()
    result = r.json()
    log_action("printify_agent", f"Product {product_id} published to Etsy")
    return result


def _get_published_listing_id(product_id: str, retries: int = 5, delay: int = 6) -> str:
    """
    Poll the product endpoint until Etsy assigns a listing ID.
    Printify's publish is async — the external.id may take a few seconds.
    """
    for attempt in range(retries):
        r = httpx.get(
            f"{PRINTIFY_BASE}/shops/{_shop_id()}/products/{product_id}.json",
            headers=_headers(),
            timeout=30,
        )
        r.raise_for_status()
        data = r.json()
        ext_id = str(data.get("external", {}).get("id") or "")
        if ext_id and ext_id != "0":
            return ext_id
        log_action(
            "printify_agent",
            f"Waiting for Etsy listing ID (attempt {attempt + 1}/{retries})…",
        )
        time.sleep(delay)
    return ""


# ── node ──────────────────────────────────────────────────────────────────────

def printify_node(state: dict) -> dict:
    log_action("printify_agent", "Uploading designs to Printify")
    errors   = list(state.get("errors", []))
    designs  = state.get("generated_designs", [])
    products = []
    etsy_listings = []

    if not designs:
        log_action("printify_agent", "No designs to upload — skipping.", "warning")
        return {**state, "printify_products": [], "etsy_listings": [], "errors": errors}

    for design in designs:
        path  = design.get("design_path", "")
        brief = design.get("brief", {})
        niche = brief.get("niche", "unknown")

        log_action("printify_agent", f"Processing design: {path}  ({niche})")

        try:
            # 1. Upload image
            image_id = upload_image(path)

            # 2. Find blueprint + working provider
            product_type = brief.get("product_type", "t-shirt")
            blueprint_id = BLUEPRINTS.get(product_type, 5)
            provider_id, variants = _find_working_provider(blueprint_id, product_type)
            log_action("printify_agent", f"Using provider={provider_id}, {len(variants)} variants")

            # 3. Create product with SEO content already included
            product = create_product(image_id, brief, provider_id, variants)
            product_id = product["id"]

            # 4. Publish to Etsy
            publish_result = publish_product(product_id)

            # 5. Retrieve Etsy listing ID (async on Printify side)
            etsy_listing_id = _get_published_listing_id(product_id)
            listing_url = (
                f"https://www.etsy.com/listing/{etsy_listing_id}"
                if etsy_listing_id else ""
            )

            if etsy_listing_id:
                log_action("printify_agent", f"Live on Etsy: {listing_url}")
                # Track in SQLite to avoid duplicate listings on future loops
                if not is_duplicate(etsy_listing_id):
                    track_listing(
                        listing_id=etsy_listing_id,
                        url=listing_url,
                        printify_id=product_id,
                        title=brief.get("seo_title") or brief.get("suggested_text", ""),
                        niche=niche,
                    )
                etsy_listings.append({
                    "listing_id":  etsy_listing_id,
                    "listing_url": listing_url,
                    "title":       brief.get("seo_title", ""),
                    "brief":       brief,
                })
            else:
                log_action(
                    "printify_agent",
                    "Could not retrieve Etsy listing ID — product published but ID pending",
                    "warning",
                )

            products.append(
                {
                    "printify_product_id": product_id,
                    "etsy_listing_id":     etsy_listing_id,
                    "brief":               brief,
                    "design_path":         path,
                }
            )

        except Exception as exc:
            msg = f"printify_agent failed for '{niche}': {exc}"
            log_action("printify_agent", msg, "error")
            errors.append(msg)

    log_action("printify_agent", f"Created {len(products)}/{len(designs)} products — {len(etsy_listings)} live on Etsy")
    return {**state, "printify_products": products, "etsy_listings": etsy_listings, "errors": errors}
